---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[frBase::default]
    attributes:
