name             'frBase'
maintainer       'Fast Robot, LLC'
maintainer_email 'cookbooks@fastrobot.com'
license          'apachev2'
description      'Catchall/initial base role cookbook'
long_description 'Installs/Configures users, '
version          '0.1.5'

depends 'frUser'
depends 'chef-client', '~> 11.4'
depends 'prometheus_exporters', '~> 0.15'
